# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20190515_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.CharField(choices=[('6', '\u0446\u0435\u0445 6'), ('7', '\u0446\u0435\u0445 7'), ('8', '\u0446\u0435\u0445 8'), ('9', '\u0446\u0435\u0445 9'), ('11', '\u0446\u0435\u0445 11'), ('14', '\u0446\u0435\u0445 14'), ('20', '\u0446\u0435\u0445 20'), ('26', '\u0446\u0435\u0445 26')], max_length=20, verbose_name='\u0426\u0435\u0445')),
                ('code', models.CharField(max_length=10, verbose_name='\u0418\u043d\u0432\u0435\u043d\u0442\u0430\u0440\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('model', models.CharField(max_length=20, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c')),
                ('description', models.TextField(max_length=1000, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('timetable', models.CharField(choices=[('8/5', '8 \u0447\u0430\u0441\u043e\u0432 \u0441 \u0432\u044b\u0445\u043e\u0434\u043d\u044b\u043c\u0438'), ('12/5', '12 \u0447\u0430\u0441\u043e\u0432 \u0441 \u0432\u044b\u0445\u043e\u0434\u043d\u044b\u043c\u0438'), ('24/5', '\u043a\u0440\u0443\u0433\u043b\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e \u0441 \u0432\u044b\u0445\u043e\u0434\u043d\u044b\u043c\u0438'), ('24/7', '\u043a\u0440\u0443\u0433\u043b\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e \u0431\u0435\u0437 \u0432\u044b\u0445\u043e\u0434\u043d\u044b\u0445')], max_length=30, verbose_name='\u0420\u0430\u0441\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.Participant')),
            ],
        ),
        migrations.AlterField(
            model_name='reason',
            name='code',
            field=models.CharField(max_length=10, verbose_name='\u041a\u043e\u0434'),
        ),
    ]
