# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_auto_20190525_0703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimetableDetails',
            new_name='TimetableDetail',
        ),
    ]
