# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_auto_20190525_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetabledetail',
            name='end_time2',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 2 \u0441\u043c\u0435\u043d\u044b'),
        ),
        migrations.AlterField(
            model_name='timetabledetail',
            name='end_time3',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 3 \u0441\u043c\u0435\u043d\u044b'),
        ),
        migrations.AlterField(
            model_name='timetabledetail',
            name='start_time2',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e 2 \u0441\u043c\u0435\u043d\u044b'),
        ),
        migrations.AlterField(
            model_name='timetabledetail',
            name='start_time3',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e 3 \u0441\u043c\u0435\u043d\u044b'),
        ),
    ]
