# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20190525_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_holiday_short', models.BooleanField(auto_created=True, verbose_name='\u0412 \u043f\u0440\u0435\u0434\u043f\u0440\u0430\u0437\u043d\u0438\u0447\u043d\u044b\u0435 \u0434\u043d\u0438 \u043d\u0430 \u0441\u043c\u0435\u043d\u044b \u0447\u0430\u0441 \u043a\u043e\u0440\u043e\u0447\u0435')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0440\u0430\u0441\u043f\u0438\u0441\u0430\u043d\u0438\u044f:')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.TimetableDetail')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Timetable')),
            ],
        ),
    ]
