# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_timetable_timetablecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('mac_address', models.CharField(max_length=15)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='xbee_mac',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='MAC \u043c\u043e\u0434\u0435\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='timetablecontent',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.TimetableDetail', verbose_name='\u0414\u0435\u0442\u0430\u043b\u0438'),
        ),
        migrations.AlterField(
            model_name='timetablecontent',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Timetable', verbose_name='\u0420\u0430\u0441\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
