# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_auto_20190525_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='channel',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
