# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_rawdata_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='mac_address',
            field=models.CharField(max_length=25),
        ),
    ]
