# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_auto_20190529_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
