# Generated by Django 2.2.1 on 2019-06-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('machines', '0011_rawdata_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='xbee_mac',
            field=models.CharField(blank=True, choices=[('00:13:A2:00:41:6C:D1:4A', '00:13:A2:00:41:6C:D1:4A'),
                                                        ('00:13:A2:00:41:6C:D6:77', '00:13:A2:00:41:6C:D6:77')],
                                   max_length=25, null=True, verbose_name='MAC модема'),
        ),
    ]
