# Generated by Django 2.2.1 on 2019-06-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('machines', '0012_auto_20190602_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True,
                                   choices=[('AD0', 'AD0'), ("AD0'", "AD0'"), ('AD1', 'AD1'), ("AD1'", "AD1'")],
                                   max_length=5, null=True, verbose_name='Канал'),
        ),
    ]
