# Generated by Django 2.2.1 on 2019-06-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('machines', '0013_equipment_main_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='allowed_idle_interval',
            field=models.IntegerField(default=15, verbose_name='Допустимый простой, мин'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='idle_threshold',
            field=models.IntegerField(default=100, verbose_name='Порог включения'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='no_load_threshold',
            field=models.IntegerField(default=110, verbose_name='Порог холостого хода'),
        ),
        migrations.CreateModel(
            name='ClassifiedInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало периода')),
                ('end', models.DateTimeField(verbose_name='Конец периода')),
                ('automated_classification',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto_reason',
                                   to='machines.Reason', verbose_name='Вычисленная причина')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Equipment',
                                                verbose_name='Оборудование')),
                ('user_classification',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reason',
                                   to='machines.Reason', verbose_name='Причина оператора')),
            ],
        ),
    ]
