# Generated by Django 2.2.1 on 2019-06-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('machines', '0014_auto_20190610_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='is_operator',
            field=models.BooleanField(default=False, verbose_name='Указывается оператором'),
        ),
        migrations.AddField(
            model_name='reason',
            name='is_working',
            field=models.BooleanField(default=False, verbose_name='Работа'),
        ),
    ]
