# Generated by Django 2.2.1 on 2019-06-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('machines', '0015_auto_20190613_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedinterval',
            name='user_classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_reason',
                                    to='machines.Reason', verbose_name='Причина оператора'),
        ),
    ]
