# Generated by Django 2.2.1 on 2019-06-18 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0016_auto_20190613_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedinterval',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Указал причину'),
        ),
        migrations.AlterField(
            model_name='classifiedinterval',
            name='user_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='user_reason', to='machines.Reason', verbose_name='Причина оператора'),
        ),
    ]
