# Generated by Django 2.2.1 on 2019-06-25 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('machines', '0017_auto_20190618_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedinterval',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Указал причину'),
        ),
        migrations.AlterField(
            model_name='classifiedinterval',
            name='user_classification',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_operator': True}, null=True,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='user_reason',
                                    to='machines.Reason', verbose_name='Причина оператора'),
        ),
    ]
