# Generated by Django 2.2.3 on 2019-07-01 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0019_auto_20190626_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semaphore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Семафор')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Заблокировано')),
                ('locked_when', models.DateTimeField(default=datetime.datetime(2019, 7, 1, 14, 43, 58, 792764, tzinfo=utc), verbose_name='Когда заблокировано')),
                ('alert_interval', models.IntegerField(default=15, verbose_name='Количество минут до предупреждения')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[('AD0', 'AD0'), ("AD0'", "AD0'"), ('AD1', 'AD1'), ("AD1'", "AD1'")], max_length=5, null=True, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='xbee_mac',
            field=models.CharField(blank=True, choices=[('00:13:A2:00:41:6C:D1:4A', '00:13:A2:00:41:6C:D1:4A'), ('00:13:A2:00:41:6C:D6:77', '00:13:A2:00:41:6C:D6:77')], max_length=25, null=True, verbose_name='MAC модема'),
        ),
    ]
