# Generated by Django 2.2.3 on 2019-07-01 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0020_auto_20190701_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaphore',
            name='locked_when',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 15, 6, 33, 944957, tzinfo=utc), verbose_name='Когда заблокировано'),
        ),
    ]
