# Generated by Django 2.2.3 on 2019-07-02 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0021_auto_20190701_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedinterval',
            name='is_zero',
            field=models.BooleanField(blank=True, default=False, verbose_name='Нет данных'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='xbee_mac',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='MAC модема'),
        ),
        migrations.AlterField(
            model_name='semaphore',
            name='locked_when',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 13, 0, 28, 701741, tzinfo=utc), verbose_name='Когда заблокировано'),
        ),
    ]
