# Generated by Django 2.2.3 on 2019-07-02 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0022_auto_20190702_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaphore',
            name='locked_when',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 15, 7, 13, 291794, tzinfo=utc), verbose_name='Когда заблокировано'),
        ),
        migrations.CreateModel(
            name='GraphicsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.Equipment', verbose_name='Оборудование')),
            ],
        ),
    ]
