# Generated by Django 2.2.3 on 2019-07-03 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0023_auto_20190702_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaphore',
            name='locked_when',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 6, 23, 47, 786209, tzinfo=utc), verbose_name='Когда заблокировано'),
        ),
    ]
