# Generated by Django 2.2.3 on 2019-07-03 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0024_auto_20190703_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaphore',
            name='locked_when',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда заблокировано'),
        ),
    ]
