# Generated by Django 2.2.3 on 2019-07-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0028_code_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
