# Generated by Django 2.2.3 on 2019-09-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0030_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, upload_to='machines', verbose_name='Фото оборудования'),
        ),
    ]
