# Generated by Django 2.2.1 on 2019-09-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0031_equipment_image'),
        ('machines', '0029_auto_20190722_1322'),
    ]

    operations = [
    ]
