# Generated by Django 2.2.3 on 2019-10-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0031_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='xbee_mac',
            field=models.CharField(blank=True, choices=[('00:13:A2:00:41:6C:D1:4A', '00:13:A2:00:41:6C:D1:4A'), ('00:13:A2:00:41:6C:D6:77', '00:13:A2:00:41:6C:D6:77')], max_length=25, null=True, verbose_name='MAC модема'),
        ),
    ]
