# Generated by Django 2.2.1 on 2019-10-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0032_auto_20191002_1101'),
        ('machines', '0032_merge_20190920_1535'),
    ]

    operations = [
    ]
