# Generated by Django 2.2.3 on 2019-11-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0032_auto_20191002_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='xbee_mac',
            field=models.CharField(blank=True, choices=[('00:13:A2:00:41:0A:4B:11', '00:13:A2:00:41:0A:4B:11'), ('00:13:A2:00:41:0A:4B:17', '00:13:A2:00:41:0A:4B:17'), ('00:13:A2:00:41:6C:D1:4A', '00:13:A2:00:41:6C:D1:4A'), ('00:13:A2:00:41:6C:D6:77', '00:13:A2:00:41:6C:D6:77')], max_length=25, null=True, verbose_name='MAC модема'),
        ),
        migrations.AlterField(
            model_name='timetablecontent',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='machines.TimetableDetail', verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='timetablecontent',
            name='timetable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='machines.Timetable', verbose_name='Расписание'),
        ),
    ]
