# Generated by Django 2.2.1 on 2019-11-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0033_merge_20191002_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='xbee_mac',
            field=models.CharField(blank=True, choices=[('00:13:A2:00:41:0A:4B:11', '00:13:A2:00:41:0A:4B:11'), ('00:13:A2:00:41:0A:4B:17', '00:13:A2:00:41:0A:4B:17'), ('00:13:A2:00:41:6C:D1:4A', '00:13:A2:00:41:6C:D1:4A'), ('00:13:A2:00:41:6C:D6:77', '00:13:A2:00:41:6C:D6:77')], max_length=25, null=True, verbose_name='MAC модема'),
        ),
    ]
