# Generated by Django 2.2.3 on 2019-11-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0033_auto_20191125_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='machines.Timetable', verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='timetablecontent',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detail', to='machines.TimetableDetail', verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='timetablecontent',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timetable', to='machines.Timetable', verbose_name='Расписание'),
        ),
    ]
