# Generated by Django 3.0 on 2020-03-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0034_auto_20191125_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[], max_length=5, null=True, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='workshop',
            field=models.CharField(choices=[('6', 'цех 6'), ('7', 'цех 7'), ('8', 'цех 8'), ('9', 'цех 9'), ('11', 'цех 11'), ('14', 'цех 14'), ('20', 'цех 20'), ('21', 'цех 21'), ('26', 'цех 26')], max_length=20, verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='xbee_mac',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='MAC модема'),
        ),
    ]
