# Generated by Django 2.2.1 on 2019-11-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0034_auto_20191120_1920'),
        ('machines', '0034_auto_20191125_1851'),
    ]

    operations = [
    ]
