# Generated by Django 2.2.1 on 2019-12-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0035_merge_20191125_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='workshop',
            field=models.CharField(choices=[('6', 'цех 6'), ('7', 'цех 7'), ('8', 'цех 8'), ('9', 'цех 9'), ('11', 'цех 11'), ('14', 'цех 14'), ('20', 'цех 20'), ('21', 'цех 21'), ('26', 'цех 26')], max_length=20, verbose_name='Цех'),
        ),
    ]
