# Generated by Django 3.0 on 2020-02-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0035_auto_20200204_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='selectable',
        ),
    ]
