# Generated by Django 3.0 on 2020-02-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0036_remove_reason_selectable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='selectable',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
