# Generated by Django 2.2.1 on 2020-02-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0036_auto_20191218_1842'),
        ('machines', '0037_reason_selectable'),
    ]

    operations = [
    ]
