# Generated by Django 2.2.1 on 2020-03-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0038_merge_20200205_1607'),
        ('machines', '0035_auto_20200312_1022'),
    ]

    operations = [
    ]
