# Generated by Django 3.0 on 2020-08-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0039_merge_20200312_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='machine_or_furnace_sign',
            field=models.BooleanField(default=True, verbose_name='Оборудование является станком'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[('AD0', 'AD0'), ("AD0'", "AD0'"), ('AD1', 'AD1'), ("AD1'", "AD1'")], max_length=5, null=True, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='no_load_threshold',
            field=models.FloatField(verbose_name='Порог холостого хода'),
        ),
    ]
