# Generated by Django 3.0 on 2020-08-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0040_auto_20200804_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('workshop_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер цеха')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('foreman', models.CharField(blank=True, max_length=50, null=True, verbose_name='Начальник цеха')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_in_monitoring',
            field=models.BooleanField(default=False, verbose_name='В системе мониторинга'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_in_repair',
            field=models.BooleanField(default=False, verbose_name='В системе учета ремонтных работ'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='red_card_id',
            field=models.BigIntegerField(default=1000000000, verbose_name='ID красной карточки'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='repair_job_status',
            field=models.IntegerField(choices=[(0, 'В рабочем состоянии'), (1, 'Сломан, необходим ремонт'), (2, 'В ремонте')], default=0, verbose_name='Статус оборудования'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='workshop',
            field=models.IntegerField(verbose_name='Цех'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('area_number', models.IntegerField(blank=True, null=True, verbose_name='Номер участка')),
                ('green_card_id', models.BigIntegerField(verbose_name='ID зеленой карточки')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Workshop', verbose_name='Цех')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.Area', verbose_name='Участок'),
        ),
    ]
