# Generated by Django 3.0 on 2020-08-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0041_auto_20200817_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.Workshop', verbose_name='Цех'),
        ),
    ]
