# Generated by Django 3.0 on 2020-08-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0044_repair_rawdata_repair_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_rawdata',
            name='card_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID карточки'),
        ),
    ]
