# Generated by Django 3.0 on 2020-08-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0045_auto_20200827_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='green_card_id',
            field=models.CharField(max_length=50, verbose_name='ID зеленой карточки'),
        ),
        migrations.AlterField(
            model_name='data_from_scan',
            name='card_id',
            field=models.CharField(max_length=50, verbose_name='ID карточки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[], max_length=5, null=True, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='red_card_id',
            field=models.CharField(default=1000000000, max_length=50, verbose_name='ID красной карточки'),
        ),
        migrations.AlterField(
            model_name='repair_rawdata',
            name='card_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID карточки'),
        ),
    ]
