# Generated by Django 3.0 on 2020-08-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0048_repair_rawdata_repairer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='green_card_id',
            field=models.CharField(max_length=70, verbose_name='ID зеленой карточки'),
        ),
        migrations.AlterField(
            model_name='data_from_scan',
            name='card_id',
            field=models.CharField(max_length=70, verbose_name='ID карточки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='red_card_id',
            field=models.CharField(default=1000000000, max_length=70, verbose_name='ID красной карточки'),
        ),
        migrations.AlterField(
            model_name='repair_rawdata',
            name='card_id',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='ID карточки'),
        ),
        migrations.AlterField(
            model_name='repairer',
            name='card_id',
            field=models.CharField(max_length=70, verbose_name='ID карточки'),
        ),
    ]
