# Generated by Django 3.0 on 2020-09-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0049_auto_20200831_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='mac_scan',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='MAC считывателя участка'),
        ),
        migrations.AddField(
            model_name='data_from_scan',
            name='mac_scan',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='MAC считывателя участка'),
        ),
    ]
