# Generated by Django 3.0 on 2020-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0050_auto_20200903_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Наименование')),
                ('descr', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
