# Generated by Django 3.0 on 2020-09-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0051_complex'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='in_complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='machines.Complex', verbose_name='Входит в комплекс'),
        ),
    ]
