# Generated by Django 3.0 on 2020-09-25 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0052_equipment_in_complex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair_reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='repair_rawdata',
            name='repair_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Repair_reason', verbose_name='Причина поломки'),
        ),
    ]
