# Generated by Django 3.0 on 2020-10-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0053_auto_20200925_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_limit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Является лимитированным оборудованием'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[('AD0', 'AD0'), ("AD0'", "AD0'"), ('AD1', 'AD1'), ("AD1'", "AD1'")], max_length=5, null=True, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='repair_rawdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время'),
        ),
    ]
