# Generated by Django 3.0 on 2020-10-19 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0054_auto_20201002_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_rawdata',
            name='repair_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='repair_reason',
            name='is_machines_operator_reason',
            field=models.BooleanField(blank=True, null=True, verbose_name='Причина указывается оператором станка'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[], max_length=5, null=True, verbose_name='Канал'),
        ),
        migrations.CreateModel(
            name='Repair_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Начало периода')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Конец периода')),
                ('repair_job_status', models.IntegerField(blank=True, choices=[(0, 'В рабочем состоянии'), (1, 'Сломан, необходим ремонт'), (2, 'В ремонте')], null=True, verbose_name='Статус оборудования')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Equipment', verbose_name='Оборудование')),
            ],
        ),
    ]
