# Generated by Django 3.0 on 2020-10-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0055_auto_20201019_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_rawdata',
            name='repair_comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий'),
        ),
    ]
