# Generated by Django 3.0 on 2020-10-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0056_auto_20201023_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator_reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='repair_reason',
            name='is_machines_operator_reason',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[('AD0', 'AD0'), ("AD0'", "AD0'"), ('AD1', 'AD1'), ("AD1'", "AD1'")], max_length=5, null=True, verbose_name='Канал'),
        ),
        migrations.AddField(
            model_name='repair_rawdata',
            name='operator_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Operator_reason', verbose_name='Причина поломки'),
        ),
    ]
