# Generated by Django 3.0 on 2020-10-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0058_auto_20201026_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair_statistics',
            name='end',
        ),
        migrations.RemoveField(
            model_name='repair_statistics',
            name='start',
        ),
        migrations.AddField(
            model_name='repair_statistics',
            name='de_facto',
            field=models.DurationField(blank=True, null=True, verbose_name='Время работы с учетом расписания'),
        ),
        migrations.AddField(
            model_name='repair_statistics',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца периода'),
        ),
        migrations.AddField(
            model_name='repair_statistics',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время конца периода'),
        ),
        migrations.AddField(
            model_name='repair_statistics',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала периода'),
        ),
        migrations.AddField(
            model_name='repair_statistics',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала периода'),
        ),
        migrations.AlterField(
            model_name='repair_rawdata',
            name='repair_reason',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Repair_reason', verbose_name='Причина поломки'),
        ),
        migrations.AlterField(
            model_name='repair_rawdata',
            name='repairer_master_reason',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Repairer_master_reason', verbose_name='Причина поломки'),
        ),
    ]
