# Generated by Django 3.0 on 2020-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0059_auto_20201029_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[], max_length=5, null=True, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='timetable',
            field=models.CharField(choices=[('8/5', '8 часов с выходными'), ('24/7', 'круглосуточно без выходных')], max_length=30, verbose_name='Расписание'),
        ),
    ]
