# Generated by Django 3.0 on 2020-10-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0060_auto_20201030_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='repair_job_status',
            field=models.IntegerField(choices=[(0, 'В рабочем состоянии'), (1, 'Сломан, необходим ремонт'), (2, 'В ремонте')], default=2, verbose_name='Статус оборудования'),
        ),
    ]
