# Generated by Django 3.0 on 2020-11-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0061_auto_20201030_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[('AD0', 'AD0'), ("AD0'", "AD0'"), ('AD1', 'AD1'), ("AD1'", "AD1'")], max_length=5, null=True, verbose_name='Канал'),
        ),
    ]
