# Generated by Django 3.0 on 2021-01-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0064_repair_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='dimension_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Дельта для измерения простоя'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='problem_machine',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Новый алгоритм измерения простоев'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[('AD0', 'AD0'), ('AD1', 'AD1')], max_length=5, null=True, verbose_name='Канал'),
        ),
        migrations.CreateModel(
            name='Minute_interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Начало промежутка')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Конец промежутка')),
                ('work_check', models.BooleanField(blank=True, null=True, verbose_name='Оборудование работает?')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Equipment', verbose_name='Оборудование')),
            ],
        ),
    ]
