# Generated by Django 3.0 on 2021-02-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0066_auto_20210201_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trinity_interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.DateTimeField(blank=True, null=True, verbose_name='Начало промежутка')),
                ('ending', models.DateTimeField(blank=True, null=True, verbose_name='Конец промежутка')),
                ('work_check', models.BooleanField(blank=True, null=True, verbose_name='Оборудование работает?')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Equipment', verbose_name='Оборудование')),
                ('user_reason', models.ForeignKey(blank=True, limit_choices_to={'is_operator': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Reason', verbose_name='Причина оператора')),
            ],
        ),
        migrations.CreateModel(
            name='Hour_interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.DateTimeField(blank=True, null=True, verbose_name='Начало промежутка')),
                ('ending', models.DateTimeField(blank=True, null=True, verbose_name='Конец промежутка')),
                ('work_check', models.BooleanField(blank=True, null=True, verbose_name='Оборудование работает?')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Equipment', verbose_name='Оборудование')),
                ('trinity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Trinity_interval', verbose_name='Промежуток входит в 3-часовой интервал')),
                ('user_reason', models.ForeignKey(blank=True, limit_choices_to={'is_operator': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Reason', verbose_name='Причина оператора')),
            ],
        ),
        migrations.AddField(
            model_name='minute_interval',
            name='hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Hour_interval', verbose_name='Промежуток входит в часовой интервал'),
        ),
    ]
