# Generated by Django 2.2.19 on 2021-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0067_auto_20210202_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('mac', models.CharField(max_length=50, verbose_name='MAC координатора')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[('AD0', 'AD0'), ("AD0'", "AD0'"), ('AD1', 'AD1'), ("AD1'", "AD1'")], max_length=5, null=True, verbose_name='Канал'),
        ),
    ]
