# Generated by Django 2.2.19 on 2021-04-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0068_auto_20210401_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ip координатора'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Coordinator', verbose_name='Координатор'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='mac',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC координатора'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование'),
        ),
    ]
