# Generated by Django 2.2.19 on 2021-05-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0069_auto_20210401_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Канал'),
        ),
    ]
