# Generated by Django 3.0 on 2021-06-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0071_auto_20210615_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='main_channel',
            field=models.CharField(blank=True, choices=[], max_length=5, null=True, verbose_name='Канал'),
        ),
    ]
