# Generated by Django 3.0 on 2021-07-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('machines', '0073_area_add_green_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование предприятия')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Группа пользователей')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Company', verbose_name='Предприятие'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Company', verbose_name='Предприятие'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Company', verbose_name='Предприятие'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Company', verbose_name='Предприятие'),
        ),
    ]
