# Generated by Django 3.0 on 2020-12-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctuary', '0002_auto_20201126_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU_RAM_DISK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата/Время')),
                ('ip', models.CharField(max_length=100, verbose_name='IP адрес')),
                ('cpu', models.FloatField(max_length=50, verbose_name='ЦПУ')),
                ('ram', models.FloatField(max_length=50, verbose_name='Память')),
                ('disk', models.FloatField(max_length=50, verbose_name='Диск')),
            ],
        ),
        migrations.AddField(
            model_name='object_list',
            name='cpu',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='ЦПУ'),
        ),
        migrations.AddField(
            model_name='object_list',
            name='disk',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Диск'),
        ),
        migrations.AddField(
            model_name='object_list',
            name='is_in_monitoring_cpu',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Участвует в мониторинге параметров сервера'),
        ),
        migrations.AddField(
            model_name='object_list',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='object_list',
            name='ram',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Память'),
        ),
    ]
