# Generated by Django 2.2.19 on 2021-05-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_auto_20210519_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_report',
            name='working_out',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
    ]
