# Generated by Django 2.2.1 on 2021-06-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_auto_20210519_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование работ'),
        ),
    ]
