# Generated by Django 3.0 on 2021-06-18 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_auto_20210615_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='create',
            new_name='creating',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='creating',
        ),
    ]
