# Generated by Django 2.2.1 on 2021-06-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0005_auto_20210618_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='nothing',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Не указано'),
        ),
    ]
